services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    volumes:
      - .:/bot
      - ./logs:/bot/logs
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
